// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56gtxaaG48IZqQAuQMZnRvWvqTJ5WbLM',
    appId: '1:943152405737:web:ae3cf64ad426bde0dce478',
    messagingSenderId: '943152405737',
    projectId: 'school-carpool-csp1',
    authDomain: 'school-carpool-csp1.firebaseapp.com',
    databaseURL: 'https://school-carpool-csp1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'school-carpool-csp1.appspot.com',
    measurementId: 'G-X5NJCDV6TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZy5aFxa7OGpgnAFvVX-ozsCZ71DJWCbA',
    appId: '1:943152405737:android:5457e3555963406fdce478',
    messagingSenderId: '943152405737',
    projectId: 'school-carpool-csp1',
    databaseURL: 'https://school-carpool-csp1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'school-carpool-csp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCkbiuwOi3OKePytw8N2ptwHSEtBatzA',
    appId: '1:943152405737:ios:f1b1f4fc2facef5bdce478',
    messagingSenderId: '943152405737',
    projectId: 'school-carpool-csp1',
    databaseURL: 'https://school-carpool-csp1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'school-carpool-csp1.appspot.com',
    androidClientId: '943152405737-4igp2ltm5gqsco0stb3r06e52v12sha0.apps.googleusercontent.com',
    iosClientId: '943152405737-jheatv57d64h92jk6hlugo81ivhpqhq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideShare',
  );
}
